#!/usr/bin/env python
from __future__ import unicode_literals
import logging
import os
import sys

base_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
sys.path.insert(0, base_path)

from migrate.versioning.shell import main
from balanced_notify import config

def setup_logging():
    logging.basicConfig()
    logger = logging.getLogger('sqlalchemy.engine')
    logger.setLevel(logging.INFO)

    script = open('migration.sql', 'w')

    h2 = logging.StreamHandler(script)
    logger.addHandler(h2)


if __name__ == '__main__':
    argv = sys.argv
    argv = [x for x in argv if x != '--log-migrations']
    if len(argv) != len(sys.argv):
        setup_logging()
    argv = argv[1:]

    # for some weird reason, debug is a fucking string in migrate.
    main(argv=argv,
         url=config['SQLALCHEMY_DATABASE_URI'],
         repository=config['SQLALCHEMY_MIGRATE_REPO'],
         debug='False')
